#!/bin/sh
#
# Script to migrate sysvinit project source code from subversion to git.
# Used february 2018.

authorsmap=$(tempfile)
cat > $authorsmap <<EOF
pere = Petter Reinholdtsen <pere@hungry.com>
wfink = Werner Fink <werner@suse.de>
EOF

# FIXME figure out why the tag from the tags directory is missing.

git svn clone http://svn.savannah.nongnu.org/svn/sysvinit/sysvinit \
    --authors-file=$authorsmap \
    --no-metadata \
    --tags=tags \
    --trunk=trunk \
    --prefix=sysvinit/ \
    sysvinit-git
rm $authorsmap

(
    cd sysvinit-git
    for tag in `git branch -r | grep "tags/" | sed 's/ sysvinit\/tags\///'`; do
        git tag -a -m"Converting SVN tags" $tag refs/remotes/sysvinit/tags/$tag
    done
)

(
    cd sysvinit-git
    git remote add origin ssh://git.savannah.gnu.org:/srv/git/sysvinit.git
)
